### PR TITLE
Pint web UI

### PR DESCRIPTION
**Pull request by ikapelyukhin**

### CODE REVIEW

**Comment by ikapelyukhin** [comment]
@jesusbv @bear454 @aosthof please review!
I don't have permissions on this repo apparently.

**Comment by ikapelyukhin** [comment]
@bear454 did you see how the page looks at the most recent commit on this branch?

**Comment by jeremy-moffitt** [comment]
in addition to the comments above, I believe this is supposed to land at https://github.com/SUSE-Enceladus/public-cloud-info-client-ui  rather than in the service repo?  If thats the case it would make sense to close this PR

**Comment by ikapelyukhin** [comment]
> in addition to the comments above, I believe this is supposed to land at https://github.com/SUSE-Enceladus/public-cloud-info-client-ui rather than in the service repo? If thats the case it would make sense to close this PR

Oh yes, we've decided to move it into a separate repo during the team workshop. I've created the repo but haven't moved the files yet.

I am going to close this PR.

**Pull request closed without merging**
