### PR TITLE
Error handling

### PR DESCRIPTION
**Pull request by mbelur**
The commit adds some error handling around invalid data obtained via the request.

### CODE REVIEW

**Review by jeremy-moffitt — APPROVED** [review]
LGTM!

**Review by chajain — APPROVED** [review]
Looks good to me

**Comment by jeremy-moffitt** [comment]
ran the function tests to try out this fix... without this fix, 107 of the functional tests fail, with it only 32 fail! definitely a move in the right direction

**Review by guangyee — APPROVED** [review]

**Review by guangyee — CHANGES_REQUESTED** [review]
Don't merge yet. I think we maybe able to use subquery for this.

**Review by guangyee — APPROVED** [review]
LGTM. We'll improve the SQL joins on the next patch.

**Pull request merged**
