### PR TITLE
Summarize response times at end of load test

### PR DESCRIPTION
**Pull request by jeremy-moffitt**
Track the response times of the requests from the load generator and print a summary at the end

### CODE REVIEW

**Review by guangyee — APPROVED** [review]
looks good

**Review by mbelur — COMMENTED** [review]
Looks Good. Should we keep track of the response time based on the API call type separately to give us average response time data specific to the type of call?

**Comment by jeremy-moffitt** [comment]
> Looks Good. Should we keep track of the response time based on the API call type separately to give us average response time data specific to the type of call?

That sounds like a reasonable next enhancement. If this looks ok as-is, maybe we merge this one and then as time allows I can add that improvement (also pondering adding a little ascii graph, but that might be beyond my abilities ;-))

**Comment by mbelur** [comment]
> > Looks Good. Should we keep track of the response time based on the API call type separately to give us average response time data specific to the type of call?
> 
> That sounds like a reasonable next enhancement. If this looks ok as-is, maybe we merge this one and then as time allows I can add that improvement (also pondering adding a little ascii graph, but that might be beyond my abilities ;-))

sounds good.

**Review by mbelur — APPROVED** [review]

**Pull request merged**
