### PR TITLE
Add cspname column to amazonimages table (CSE-289)

### PR DESCRIPTION
**Pull request by guangyee**

### CODE REVIEW

**Review by rtamalin — APPROVED** [review]
LGTM

**Review by KeithMnemonic — APPROVED** [review]
LGTM

**Comment by jeremy-moffitt** [comment]
Don't merge this at this point... it may not be needed after all.

**Comment by jeremy-moffitt** [comment]
per discussion, a fix in mashhouse will render this unnecessary, closing the PR

**Pull request closed without merging**
